books/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.listBooks, name="books"),
    path("add-book", views.addBook, name="add-book"),
    path("add-author", views.addAuthor, name="add-author")
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("add-publisher", views.addPublisher, name="add-publisher"),
    path("add-genre", views.addGenre, name="add-genre"),
    path("add-country", views.addCountry, name="add-country"),
]

library_project/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("users/", include("users.urls")),
    path("books/", include("books.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

books/models.py
from django.db import models

# Create your models here.

books/models/author.py
from django.db import models
from core.models import Person
from core.models import Country


class Author(Person):
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    biography = models.TextField(blank=True)
    personal_website = models.URLField(blank=True, null=True)
    picture = models.ImageField(upload_to="images/authors/")

books/models/book.py
from django.db import models
from django.core.validators import RegexValidator
from core.models import Content
from .author import Author


class Book(Content):
    isbn = models.CharField(max_length=13, validators=[
                            RegexValidator(regex="^(97(8|9))?\d{9}(\d|X)$", message="Insira um ISBN.")])
    pages = models.PositiveIntegerField()
    format = models.CharField(max_length=10, choices=[(
        "hardcover", "Capa Dura"), ("paperback", "Capa Mole")])
    cover = models.ImageField(upload_to="images/books/")
    authors = models.ManyToManyField(Author, related_name="books")

    def __str__(self):
        return self.title

books/forms.py
from django.forms import ModelForm
from django import forms
from .models import Book, Author


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ["first_name", "last_name", "birthdate",
                  "biography", "personal_website", "country", "picture"]
        widgets = {
            "birthdate": forms.DateInput(attrs={"type": "date"})
        }
        labels = {
            "first_name": "Nome",
            "last_name": "Apelido",
            "birthdate": "Data de Nascimento",
            "biography": "Biografia",
            "personal_website": "Website",
            "country": "Nacionalidade",
            "picture": "Fotografia"
        }

    def __init__(self, *args, **kwargs):
        super(AuthorForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if name == "country":
                field.widget.attrs.update({"class": "form-select mb-3"})
            else:
                field.widget.attrs.update({"class": "form-control mb-3"})


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ["title", "authors", "publisher",
                  "genre", "publication_date", "summary", "isbn", "pages", "format", "language", "cover"]
        widgets = {
            'publication_date': forms.DateInput(attrs={"type": "date"})
        }
        labels = {
            "title": "Título",
            "authors": "Autor(es)",
            "publisher": "Editora",
            "genre": "Géneros",
            "publication_date": "Data de Publicação",
            "summary": "Resumo",
            "isbn": "ISBN",
            "pages": "Número de páginas",
            "format": "Formato",
            "language": "Idioma",
            "cover": "Capa"
        }

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            if name == "authors" or name == "publisher" or name == "genre" or name == "format" or name == "language":
                field.widget.attrs.update({"class": "form-select"})
            else:
                field.widget.attrs.update({"class": "form-control"})

books/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib import messages

from .forms import BookForm, AuthorForm
from .models import Book


# Helper Functions
def is_librarian(user):
    return user.is_authenticated and user.contact.is_librarian


def listBooks(request):
    books = Book.objects.all()
    return render(request, "books/list-books.html", {
        "books": books
    })


@user_passes_test(is_librarian, login_url="/")
def addBook(request):
    form = BookForm()

    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)

        if form.is_valid():
            book = form.save(commit=False)
            book.title = book.title.title()
            book.save()
            messages.success(request, "Novo livro adicionado com sucesso.")
            return redirect("add-book")
        else:
            messages.error(request, "Foram encontrados erros no formulário.")
            return render(request, "books/book-form.html", {
                "form": BookForm(request.POST, request.FILES)
            })

    return render(request, "books/book-form.html", {
        "form": form
    })


@user_passes_test(is_librarian, login_url="/")
def addAuthor(request):
    form = AuthorForm()

    if request.method == "POST":
        form = AuthorForm(request.POST, request.FILES)

        if form.is_valid():
            author = form.save(commit=False)
            author.first_name = author.first_name.title()
            author.last_name = author.last_name.title()
            author.save()
            messages.success(request, "Novo autor adicionado com sucesso.")
            return redirect("add-author")
        else:
            messages.error(request, "Foram encontrados erros no formulário.")
            return render(request, "books/author-form.html", {
                "form": AuthorForm(request.POST, request.FILES)
            })

    return render(request, "books/author-form.html", {
        "form": form
    })

books/templates/books/author-form.html
{% extends "main.html" %}

{% block content %}
<main class="container mt-5 border shadow-lg rounded-4 p-5 mb-5">
    <div class="container-fluid d-flex align-items-center justify-content-center mb-3">
        <ion-icon name="add-circle-outline" class="me-4" size="large"></ion-icon>
        <h1>Adicionar Autor</h1>
    </div>
    <div class="container-sm w-75 border p-5 rounded-3">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row mb-3">
                {% for field in form %}
                {% if field.label == "Nome" or field.label == "Apelido" %}
                <div class="col">
                    <label for="" class="form-label fw-bold">{{field.label}}</label>
                    {{field}}
                    {{field.errors}}
                </div>
                {% endif %}
                {% endfor %}
            </div>
            {% for field in form %}
                {% if field.label != "Nome" and field.label != "Apelido" %}
                <label class="form-label fw-bold">{{field.label}}</label>
                {{field}}
                {{field.errors}}
                {% endif %}
            {% endfor %}  
            <input type="submit" value="Registar" class="btn btn-primary btn-lg">
        </form>
    </div>
</main>
{% endblock content %}

books/templates/books/book-form.html
{% extends "main.html" %}

{% block internal_css %}
.errorlist {
    list-style: none;
    margin: 0.5rem 0;
    padding: 1rem 2rem;
    background-color: #faa2a2;
    color: #000000;
    font-weight: bold;
}

.errors input {
    border-color: #680000;
    background-color: #fde3e3;
}

.errors label {
    color: #680000;
}
{% endblock internal_css %}

{% block content %}
    <main class="container mt-5 border shadow-lg rounded-4 p-5 mb-5">
        <div class="container-fluid d-flex align-items-center justify-content-center mb-3">
            <ion-icon name="add-circle-outline" class="me-4" size="large"></ion-icon>
            <h1>Adicionar Livro</h1>
        </div>
        <div class="container-sm w-75 border p-5 rounded-3">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div class="mb-3">
                        <label for="title" class="form-label fw-bold">{{field.label}}</label>
                        {{field}}
                        {{field.errors}}
                        {% if field.label == "Autor(es)" or field.label == "Editora" or field.label == "Géneros" or field.label == "Idioma"%}
                            {% if field.label == "Autor(es)" %}
                                <a href="{% url "add-author" %}" class="btn btn-info btn-sm text-white fw-bold mt-3">Adicionar {{field.label}}</a>
                            {% elif field.label == "Editora" %}
                                <a href="{% url "add-publisher" %}" class="btn btn-info btn-sm text-white fw-bold mt-3">Adicionar {{field.label}}</a>
                            {% elif field.label == "Géneros" %}
                                <a href="{% url "add-genre" %}" class="btn btn-info btn-sm text-white fw-bold mt-3">Adicionar {{field.label}}</a>
                            {% elif field.label == "Idioma" %}
                                <a href="{% url "add-country" %}" class="btn btn-info btn-sm text-white fw-bold mt-3">Adicionar {{field.label}}</a>
                            {% endif %}
                        {% endif %}
                    </div>              
                {% endfor %}
                <input type="submit" value="Registar" class="btn btn-primary btn-lg">
            </form>
        </div>
    </main>
{% endblock content %}

books/templates/books/list-books.html
{% extends "main.html" %}


{% block content %}
<main class="container-fluid w-75 p-5">
    <h2 class="mb-3">Pesquisa os teus livros favoritos...</h2>
    <form action="">
        <div class="input-group mb-5">
            <span class="input-group-text" id="basic-addon1">
                <ion-icon name="search-outline"></ion-icon>
            </span>
            <input type="text" class="form-control" placeholder="Pesquisar por Título, Autor, ISBN..." aria-label="Username" aria-describedby="basic-addon1">
          </div>                  
    </form>

    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-5">
        {% for book in books %}
        <div class="col">
            <div class="card">
                <img src="{{book.cover.url}}" alt="" class="card-img-top bg-primary-subtle" style="object-fit: contain; height: 15rem;"/>
                <div class="card-body">
                    <h5 class="card-title">{{book.title}}</h5>
                    {% for author in book.authors.all %}
                    <h6 class="card-title"><a href="#" class="link-secondary">{{author.first_name}} {{author.last_name}}</a></h6>
                    {% endfor %}
                    <p class="card-text">
                        <ul class="list-unstyled">
                            <li><small class="fw-bold">Editora: </small> <small>{{book.publisher}}</small></li>
                            <li><small class="fw-bold">Nº Páginas: </small> <small>{{book.pages}}</small></li>
                            <li><small class="fw-bold">Encadernação: </small> <small>{{book.get_format_display}}</small></li>
                            <li><small class="fw-bold">Quantidade: </small> <small>{{book.quantity}}</small></li>
                            <li><small class="fw-bold">1º Edição: </small> <small>{{book.publication_date}}</small></li>
                            <li style="font-size: 13px;">
                                {% for genre in book.genre.all|slice:"4" %}
                                    <span class="badge text-bg-dark p-2 mt-2">{{genre}}</span>
                                {% endfor %}
                            </li>
                        </ul>
                    </p>
                    <a href="#" class="btn btn-primary">Ver Mais</a>
                </div>
            </div>
        </div>      
        {% endfor %}

    </div>




</main>



{% endblock content %}